pub mod function;
pub use function::apply;
pub use function::cube;
pub use function::find_pos;
pub use function::not_pi;
pub use function::pi;
pub use function::square;
pub use function::sum;
pub use function::run;
